name: sam2inv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.14
  - pip
  - pip:
      - z3-solver
      - numpy
      - openai
      - pyyaml
      - fastapi
      - uvicorn
      - transformers
      - torch
      - accelerate
      - vllm
      - pydantic
