#!/usr/bin/env bash
set -euo pipefail

python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 11 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 4 --max-assign 4 --min-assign 1 --max-ifelse 1 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates L6_snapshot_chase --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 21 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 4 --max-assign 4 --min-assign 1 --max-ifelse 3 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates L5_countdown_triple,L12_monotone_increment --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 21 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 5 --max-assign 2 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates X2_gcd_convergence,X14_interval_shrinking --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 11 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 5 --max-assign 4 --min-assign 1 --max-ifelse 3 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates L19_linked_countdown --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 44 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 8 --max-assign 6 --min-assign 1 --max-ifelse 4 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates G1_linear_generic_expandable,L1_affine_accumulator,L3_proportional_stride,L11_triple_modular_step,X15_diagonal_walk --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 106 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 6 --max-assign 4 --min-assign 1 --max-ifelse 1 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates L4_conservation,L17_geometric_doubling,L18_sawtooth_modular,L20_decaying_stride,X4_coupled_counter_acc,X9_accumulated_difference,X10_prefix_sum_count,X13_convergent_pair,X18_matrix_trace,X1_geometric_growth_bound --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 21 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 6 --max-assign 3 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates L9_sliding_window,L16_min_tracking --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 21 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 7 --max-assign 3 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates L7_parity_flipflop,L15_multi_countdown --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 11 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 8 --max-assign 6 --min-assign 1 --max-ifelse 4 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates L8_saturation_guard --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 26 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 5 --max-assign 3 --min-assign 1 --max-ifelse 1 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates L2_countdown,X12_modular_equality_race,X20_amortized_credit --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 11 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 5 --max-assign 3 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates L10_piecewise_multirate --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 11 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 4 --max-assign 2 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates L13_binary_toggle --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 21 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 6 --max-assign 5 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates X17_harmonic_step_reduction,X21_carry_pair_counter --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 11 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 5 --max-assign 4 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates X5_bouncing_counter --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 21 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 7 --max-assign 6 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates X19_rolling_sum_window,X22_ramped_transfer_conservation --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 11 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 5 --max-assign 4 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates L14_cache_coherence --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 11 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 6 --max-assign 5 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates X23_alternating_swap_transfer --append

python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 125 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 6 --max-assign 3 --min-assign 1 --max-ifelse 1 --min-ifelse 0 --min-loops 2 --max-loops 2 --p-multi 1.0 --p-semantic-core 1.0 --allowed-templates prefix_sum_family,complement_step --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 125 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 5 --max-assign 2 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 2 --max-loops 2 --p-multi 1.0 --p-semantic-core 1.0 --allowed-templates gcd_compare,accumulate_family --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 125 --workers 20 --p-nonlinear 1.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 6 --max-assign 4 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 2 --max-loops 2 --p-multi 1.0 --p-semantic-core 1.0 --allowed-templates russian_multiply,accumulate_family --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 125 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 6 --max-assign 3 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 2 --max-loops 2 --p-multi 1.0 --p-semantic-core 1.0 --allowed-templates snapshot_family,accumulate_family --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 125 --workers 20 --p-nonlinear 1.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 7 --max-assign 5 --min-assign 1 --max-ifelse 1 --min-ifelse 0 --min-loops 2 --max-loops 2 --p-multi 1.0 --p-semantic-core 1.0 --allowed-templates int_sqrt_sieve,cauchy_schwarz_triple --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 125 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 8 --max-assign 6 --min-assign 1 --max-ifelse 4 --min-ifelse 0 --min-loops 2 --max-loops 2 --p-multi 1.0 --p-semantic-core 1.0 --allowed-templates mod_bucket_cascade,prefix_sum_family --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 125 --workers 20 --p-nonlinear 1.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 7 --max-assign 3 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 2 --max-loops 2 --p-multi 1.0 --p-semantic-core 1.0 --allowed-templates qr_division_step,accumulate_family --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 125 --workers 20 --p-nonlinear 1.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 6 --max-assign 3 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 2 --max-loops 2 --p-multi 1.0 --p-semantic-core 1.0 --allowed-templates fixed_point_root_refinement,saturation --append



python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 10 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 8 --max-assign 6 --min-assign 1 --max-ifelse 3 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates X24_scheduled_queue_occupancy --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 24 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 7 --max-assign 6 --min-assign 1 --max-ifelse 3 --min-ifelse 0 --min-loops 2 --max-loops 2 --p-semantic-core 1.0 --allowed-templates X25_nested_triangular_patterns,X26_nested_grid_patterns,X27_nested_block_patterns --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 32 --workers 20 --p-nonlinear 1.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 7 --max-assign 5 --min-assign 1 --max-ifelse 1 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates N9_cauchy_schwarz --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 79 --workers 20 --p-nonlinear 1.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 6 --max-assign 4 --min-assign 1 --max-ifelse 1 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates N8_int_sqrt,X6_newton_sqrt --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 32 --workers 20 --p-nonlinear 1.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 7 --max-assign 4 --min-assign 1 --max-ifelse 3 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates N5_quotient_remainder --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 32 --workers 20 --p-nonlinear 1.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 7 --max-assign 6 --min-assign 1 --max-ifelse 3 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates N10_russian_multiply --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 79 --workers 20 --p-nonlinear 1.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 9 --max-assign 7 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates N6_extended_euclid,X16_carry_chain --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 32 --workers 20 --p-nonlinear 1.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 9 --max-assign 7 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates X8_dual_phase_recurrence --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 79 --workers 20 --p-nonlinear 1.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 7 --max-assign 6 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates N1_poly_finite_diff,N11_product_by_addition --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 124 --workers 20 --p-nonlinear 1.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 8 --max-assign 7 --min-assign 1 --max-ifelse 3 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates G2_nla_generic_expandable,N2_triangular_sum,N7_geometric_affine,X3_bisection,X11_odd_sum_square --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 32 --workers 20 --p-nonlinear 1.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 6 --max-assign 4 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates N13_affine_geometric --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 79 --workers 20 --p-nonlinear 1.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 6 --max-assign 3 --min-assign 1 --max-ifelse 1 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates N3_square_sum,N4_higher_power_sums,N12_squared_invariant --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 32 --workers 20 --p-nonlinear 1.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 9 --max-assign 9 --min-assign 1 --max-ifelse 4 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates N14_quadratic_piecewise --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 32 --workers 20 --p-nonlinear 1.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 7 --max-assign 7 --min-assign 1 --max-ifelse 3 --min-ifelse 0 --min-loops 1 --max-loops 1 --p-semantic-core 1.0 --allowed-templates X7_carry_propagation_accumulator --append
