#!/usr/bin/env bash
set -euo pipefail

python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 125 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 6 --max-assign 3 --min-assign 1 --max-ifelse 1 --min-ifelse 0 --min-loops 2 --max-loops 2 --p-multi 1.0 --p-semantic-core 1.0 --allowed-templates prefix_sum_family,complement_step --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 125 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 5 --max-assign 2 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 2 --max-loops 2 --p-multi 1.0 --p-semantic-core 1.0 --allowed-templates gcd_compare,accumulate_family --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 125 --workers 20 --p-nonlinear 1.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 6 --max-assign 4 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 2 --max-loops 2 --p-multi 1.0 --p-semantic-core 1.0 --allowed-templates russian_multiply,accumulate_family --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 125 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 6 --max-assign 3 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 2 --max-loops 2 --p-multi 1.0 --p-semantic-core 1.0 --allowed-templates snapshot_family,accumulate_family --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 125 --workers 20 --p-nonlinear 1.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 7 --max-assign 5 --min-assign 1 --max-ifelse 1 --min-ifelse 0 --min-loops 2 --max-loops 2 --p-multi 1.0 --p-semantic-core 1.0 --allowed-templates int_sqrt_sieve,cauchy_schwarz_triple --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 125 --workers 20 --p-nonlinear 0.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 8 --max-assign 6 --min-assign 1 --max-ifelse 4 --min-ifelse 0 --min-loops 2 --max-loops 2 --p-multi 1.0 --p-semantic-core 1.0 --allowed-templates mod_bucket_cascade,prefix_sum_family --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 125 --workers 20 --p-nonlinear 1.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 7 --max-assign 3 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 2 --max-loops 2 --p-multi 1.0 --p-semantic-core 1.0 --allowed-templates qr_division_step,accumulate_family --append
python3 /home/yangfp/SAM2INV/loop_factory/batch_pipeline.py --num-candidates 5 --work-dir test --target-count 125 --workers 20 --p-nonlinear 1.0 --max-params 2 --min-params 0 --min-vars 1 --max-vars 6 --max-assign 3 --min-assign 1 --max-ifelse 2 --min-ifelse 0 --min-loops 2 --max-loops 2 --p-multi 1.0 --p-semantic-core 1.0 --allowed-templates fixed_point_root_refinement,saturation --append